### ISSUE TITLE
User/active list doesn't provide all users

### ISSUE THREAD

**Issue by jonfriesen** [MegaMakers/sync-twitter#2]
Discourse has a weird user api and the users/active endpoint doesn't give all of the users. To actually iterate over all of the users we need to take another approach:

It is possible to get a list of all users via the groups API endpoint available to admins.

You’ll have to iterate over the following groups:

```
trust_level_0
trust_level_1
trust_level_2
trust_level_3
trust_level_4
```
But they do support both limit and offset parameters:

`/groups/trust_level_0/members.json?limit=50&offset=50`

*Update - Adding more detail*
The trust level endpoints return a json object that looks like:
```json
{
"members": [
{
"id": 100,
"username": "someuser",
"avatar_template": "/user_avatar/club.megamaker.co/someuser/{size}/335_1.png",
"name": "Some User",
"title": null,
"last_posted_at": null,
"last_seen_at": null
},
]
...
"meta": {
"total": 569,
"limit": 50,
"offset": 50
}
}
```

we will have to do a user lookup on each of these to get user fields (where twitter is located). Using the member id we can do a get call:

```php
function fetchUser($userId)
{
    return fetch('https://club.megamaker.co/admin/users/'.$userId.'.json)');
}
```
The above function needs to user the user id (_not the username as it currently does_). This will return a large json blob of the user data. The `1` user field is going to be the twitter handle, this blob looks like:
```json
{
"id": 151,
"username": "jon",
"avatar_template": "/user_avatar/club.megamaker.co/jon/{size}/361_1.png",
...
"user_fields": {
"1": "jonfriesen"
},
...
}
```

**Comment by dehenne** [comment]
I solved this a little differently. I don't like the solution with the trust levels.

According to the documentary, its possible to add a `page` get param.
https://docs.discourse.org/#tag/Users%2Fpaths%2F~1admin~1users~1list~1%7Bflag%7D.json%2Fget

i prefer to iterate through this and hope that if i call up a page that does not contain any users, discourse will also give me an empty result. but you would have to check it out :-/

**Comment by dehenne** [comment]
You closed the issue? Does it work?

**Comment by jonfriesen** [comment]
When you type "fixes" and I merge a PR it will auto close the bug. I haven't tested it yet ;) Not home from work yet
